"""Foo migration

Revision ID: 17fac2966f08
Revises: None
Create Date: 2017-12-07 16:11:30.108705
"""

# revision identifiers, used by Alembic.
revision = '17fac2966f08'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
